apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-dev-ingress
  namespace: default
  labels:
    app: portfolio
    env: dev
spec:
  ingressClassName: traefik
  rules:
  - host: dev.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-dev-service
            port:
              number: 80