apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: petarpdev/devops-portfolio
    newTag: dev-e11acaed7a61d5277b03ac143693d70e85631b16