apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: petarpdev/devops-portfolio
    newTag: dev-c937d2f75879f21ce6e4f66df1f09a6fc3204a30