apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: petarpdev/devops-portfolio
    newTag: dev-fb26123297a7836b30e9ebbcd03623717b147462