apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: petarpdev/devops-portfolio
    newTag: prod-8b9b84c99eef7e36efd5ffdc90d067f8f7f5461f