apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: petarpdev/devops-portfolio
    newTag: prod-a7c144dc3693d2716018e4e185b70a8e59784620